version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "HorseRacingAPI"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1h1tn68ekm64t"
s3_prefix = "HorseRacingAPI"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

